### ISSUE TITLE
user-agent mapped wrongly

### ISSUE THREAD

**Issue by TomTsong** [ua-parser/uap-go#85] opened 2024-02-04 09:30 UTC
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[120.0.0.0](http://120.0.0.0/) Safari/537.36

**Comment by dgoldstein0** [comment] 2024-02-11 06:35
please give more information.  what version of uap-go are you using? what output do you expect?

I ran this through the version I have installed - which is admittedly not the latest - but it gave what looked like the right results to me.

**Comment by dgoldstein0** [comment] 2024-06-11 07:09
I can't reproduce anything wrong with detecting this user agent.  Closing as not reproducible, if you can provide a repro with exactly what you expect the output to be, I'd reconsider.  But most misdetections should be issues for the uap-core repo which defines the list of regexs we use.

**Closed** 2024-06-11 07:09 UTC
