### ISSUE TITLE
cache.go causing issue

### ISSUE THREAD

**Issue by schien-dong** [ua-parser/uap-go#82] opened 2023-09-05 11:54 UTC
The newly introduced cache.go is giving the following errors:

```
ua-parser/uap-go/uaparser/cache.go:10:17: undefined: lru.ARCCache
ua-parser/uap-go/uaparser/cache.go:11:17: undefined: lru.ARCCache
ua-parser/uap-go/uaparser/cache.go:12:17: undefined: lru.ARCCache
ua-parser/uap-go/uaparser/cache.go:23:22: undefined: lru.NewARC
ua-parser/uap-go/uaparser/cache.go:27:18: undefined: lru.NewARC
ua-parser/uap-go/uaparser/cache.go:31:25: undefined: lru.NewARC
```

Comparing to the previous working copy, this file is the only difference. Is it included by accident?

**Comment by schien-dong** [comment] 2023-09-05 18:31
The hashicorp/golang-lru is residing in the %%GOPATH%%/src/github.com/ folder. cache.go is not resolving still...

**Comment by ammario** [comment] 2023-09-08 18:10
I suspect the issue is outside of this project and due to your GOPATH setup. I suggest reverting to the previous version of this library if you don't need the performance enhancement. Its functionality is quite complete.

**Comment by dgoldstein0** [comment] 2023-12-26 07:58
doesn't sound like there's an action item here so closing for cleanliness.

**Closed** 2023-12-26 07:58 UTC
